# Generated by Django 3.2.9 on 2021-11-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
